### ISSUE TITLE
Feature request: color config for remote

### ISSUE THREAD

**Issue by ArnolddeBolster** [dezihh/my-harmony-card#10]
Button color is missing:
I would like the same color config like madmicio's:
colorscheme i used:
colors:
active-background-button-color: '#0080ff'
deactive-background-button-color: '#f2f0fa'
button-border-standard: rgba(0, 128, 255, .5)
state-icon-active-color: '#0080ff'
buttons: '#363538'
text: white
background: black

![image](https://github.com/dezihh/my-harmony-card/assets/71195708/23427511-39fe-4b52-a4b2-cc9ff5a30878)

**Comment by ArnolddeBolster** [comment]
For me there is one color missing to get it right in black remote.
These are the available colors in the remote:
![image](https://github.com/user-attachments/assets/c2d33ac0-169e-43bf-a8da-0cc02c658aa3)

and this one is missing:
![image](https://github.com/user-attachments/assets/c21842bc-b898-4ae0-9aca-027180e56c97)

**Comment by dezihh** [comment]
Your request is not 100% clear to me? 
What do you like? Post 2 could make sense in my eyes but you are requesting some more in your first post. Especially state and active /deactive state we don't have except in the actions view, so it make no sense, doesn't it?

**Comment by ArnolddeBolster** [comment]
when I use your colorscheme I get this:
![image](https://github.com/user-attachments/assets/0ecd9041-acfd-4549-af5f-6f3e89465f8d)
and with the extra buttons color I get the same result as the madmacios remote I uploaden earlier

**Comment by ArnolddeBolster** [comment]
if this change will be made I can remove the madmacios and use this exelent integration instead

**Comment by dezihh** [comment]
Please wait for next release, it is nearly ready. I think, there are some good Features for you in. I think, in one or two weeks, it is ready

**Comment by dezihh** [comment]
since v1.30 implemented
