### ISSUE TITLE
Feature request: extra buttons for apps.

### ISSUE THREAD

**Issue by ArnolddeBolster** [dezihh/my-harmony-card#11]
Improvement would be Extra sources (like madmicio's) for:
sources:
- name: Netflix
icon: mdi:netflix
- name: Disney+
icon: disney
- name: Prime Video
icon: si:amazonaws
- name: Viaplay info
icon: si:v

![image](https://github.com/dezihh/my-harmony-card/assets/71195708/08239566-e2fa-4a8a-8561-5b5430270280)

**Comment by dezihh** [comment]
Feaured in v1.10.0

**Comment by ArnolddeBolster** [comment]
Great news,

the only thing I now get the message Plugin dezihh/my-harmony-card> Repository structure for 1.10.3 is not compliant
when trying to download/install it

kind regards

Arnold
________________________________
Van: dezihh ***@***.***>
Verzonden: zondag 18 augustus 2024 20:05
Aan: dezihh/my-harmony-card ***@***.***>
CC: olybol ***@***.***>; Author ***@***.***>
Onderwerp: Re: [dezihh/my-harmony-card] Feature request: extra buttons for apps. (Issue #11)


Feaured in v1.10.0
