### ISSUE TITLE
Feature request: Extra button for popup channels

### ISSUE THREAD

**Issue by ArnolddeBolster** [dezihh/my-harmony-card#12]
and a button for a popup I use for (favorite) TV channels:
![image](https://github.com/dezihh/my-harmony-card/assets/71195708/d0bea8b6-5d97-4c39-a6e4-332c0cc510f1)

![image](https://github.com/dezihh/my-harmony-card/assets/71195708/8f870f04-b7d0-4ac7-a90b-6981c51cea4e)

**Comment by dezihh** [comment]
Featured in v1.10.0

**Comment by ArnolddeBolster** [comment]
Nice work !!!

123 Favorites popup Button works on my laptop browser
but not on my smartphone browser(s) Edge/Samsung/Chrome)
No pop-up is on screen




________________________________
Van: dezihh ***@***.***>
Verzonden: zondag 18 augustus 2024 20:04
Aan: dezihh/my-harmony-card ***@***.***>
CC: olybol ***@***.***>; Author ***@***.***>
Onderwerp: Re: [dezihh/my-harmony-card] Feature request: Extra button for popup channels (Issue #12)


Featured in v1.10.0

**Comment by dezihh** [comment]
Thank you!
Regarding your last Post, you are right :-(
I have tested it yesterday. On Apple mobile devices the popup is not coming up. Maybe a bug in framework of Home Assistant? I have to investigate....

**Comment by dezihh** [comment]
Fixed in v 1.21.0. Should work now on mobile devices too!
Please reopen, if you have still trouble in opening favorites on mobile devices...

**Comment by ArnolddeBolster** [comment]
Perfect, well done !!!!
