### ISSUE TITLE
can not install latest version

### ISSUE THREAD

**Issue by ArnolddeBolster** [dezihh/my-harmony-card#14]
![image](https://github.com/user-attachments/assets/ec8d5829-7d5e-474c-a048-4e5303a524b4)

**Comment by rujelus22** [comment]
I am getting the same error message with the newest version

**Comment by dezihh** [comment]
Unfortunately, you are right. I have some trouble with auftomatic upload of icons. This has destroyed the new release :-( Give me some days, I'll try to fix it...

**Comment by dezihh** [comment]
Apologies for the inconvenience, everyone. The changes in the release creation process didn’t work as expected in practice. Starting from version 1.20.0, the installation should work smoothly again.
