### ISSUE TITLE
Activity Listen to Radio device can't handle command for channel choice

### ISSUE THREAD

**Issue by ArnolddeBolster** [dezihh/my-harmony-card#15]
Perfect last chages in the new version !!!

But my activity Listen to Radio DAB popup for channelchoice is working and nice with radio icons but button number is not an exepted command for my receiver (most of them don't)

I have a popup card with behind each button a call-service for a script for a network receivder accepts API call (putted in a script)

so my question/featuire request is: 
- how can I automate a button push for the number button so it can call the script
- or can you make a routine behind the button to act like a call-service for a script
- or can you make a optional button so I can configure one of the button1-4 buttons to call a script file for my existing popup script 

This is my activity for the radio:
  Radio luisteren DAB:
    name: '41379771'
    device_id: '65398893'
    volume_device_id: '65398893'
    OK: Mute
    Rewind: PresetPrev
    Forward: PresetNext
    player_name: media_player.room1
    favorites:
      - number: 1
        image: npo1.png
      - number: 2
        image: npo2.png
      - number: 3
        image: npo3fm.jpeg
      - number: 4
        image: radio-veronica-logo.png
      - number: 5
        image: kink.png
      - number: 6
        image: radio538.png
      - number: 7
        image: qmusic.png
      - number: 8
        image: radio10.png
      - number: 9
        image: skyradio.png
      - number: 10
        image: radiowest.png
      - number: 11
        image: kink80s.png
      - number: 12
        image: kink.png
      - number: 13
        image: skyradio.png
      - number: 14
        image: qmusic.png
      - number: 15
        image: radio10.png

**Comment by dezihh** [comment]
Thank you! :-D
You are right, the favorites popup is only a shortcut, instead of entering the number on the keypad.

From my point of view, a second row of "extra buttons" (Button[5-8]), were you can call an individual service would be nice for me too. Is this sufficient for you?

If yes, forget the question below ;-)
However, if I understand right, you need anyway a way to call a service, before entering a number is possible?

**Comment by ArnolddeBolster** [comment]
entering number of keypad or shortcut is not working for all devices. It works smoothly for watching TV but when listen to radio my receiver doesn't recognize the number.
so it would be nice if the shortcut would lead to the service call / api call (i have scripts for my receiver already)
or an extra button with possibility to the service call/action for my script fot my own popup.
![image](https://github.com/user-attachments/assets/cd3f146c-b01e-44cd-a636-d3324889c213)

**Comment by dezihh** [comment]
Since v1.30 service calls implemented for that
