### ISSUE TITLE
Feature request: change row order ButtonA-D with Button1-4

### ISSUE THREAD

**Issue by ArnolddeBolster** [dezihh/my-harmony-card#19]
Excellent job  !!!! compliments to you

It's almost perfect:
![image](https://github.com/user-attachments/assets/917424b2-95ae-4b98-954e-28358dac758d)

could you change the row order:
ButtonA-D with Button1-4

for ButtonA-D is for complete remote and
Button1-4 is optional for each activity, just like the color buttons (activateCButtons)

**Comment by dezihh** [comment]
From my point of view, fixed. Ok?

**Comment by ArnolddeBolster** [comment]
new position is great !! 
but my button actions do not work anymore
![image](https://github.com/user-attachments/assets/4c7190fe-61cd-412d-9aca-598203249315)

    ButtonA:
      service: script.harmony_tv_powertoggle
      name: TV
      icon: mdi:television
      tooltip: TV
      data:
        entity_id: script.harmony_tv_powertoggle
    ButtonB:
      service: script.popup_dysonam06
      name: dysonAM07
      icon: mdi:fan
      tooltip: DysonAM07
      data:
        entity_id: script.popup_dysonam06
    ButtonC:
      service: script.google_home_mini_powertoggle
      name: Google Home Mini
      tooltip: Google Home MIni
      icon: mdi:ev-plug-type1
      data:
        entity_id: script.google_home_mini_powertoggle
    ButtonD:
      service: light.toggle
      name: Woonkamer lampen
      icon: mdi:lightbulb
      tooltip: Woonkamer lampen
      data:
        entity_id: light.woonkamer_lampen

**Comment by dezihh** [comment]
Yes, it was written inside of the update, you have to indent "data" below "service"
Example:
```
ButtonD:
  service: 
    name: light.toggle
    data:
      entity_id: light.woonkamer_lampen
  name: Woonkamer lampen
  icon: mdi:lightbulb
  tooltip: Woonkamer lampen
```
**So, I assume, you have not read the release notes, are you aware, that there are now Button[1-8]?!**

**Comment by ArnolddeBolster** [comment]
sorry I wasn't aware of it because I thought only the place of the row was changed.
I changed it and it works perfectly !!!

many many thanks !!
