### ISSUE TITLE
Wrong device saved ? and buttons do not appear /react

### ISSUE THREAD

**Issue by ArnolddeBolster** [dezihh/my-harmony-card#2]
I try to configure the remote but have some issues:
While my activities are recognized automaticly (maybe because of the harmony....conf) I'm having trouble to get buttons working.
When I open the card I see my chromecast as chosen device while in the yaml I configured my remote
![image](https://github.com/dezihh/my-harmony-card/assets/71195708/33d1dac0-15cf-48cb-8cd4-9df998191a11)

And I folowed instructions to setup Button1-4 but they do not appear in the card.

What am I doing wrong ?

type: custom:my-harmony-card
name: Harmony
entity: remote.woonkamer
tooltip: true
activities:
  PowerOff:
    name: Poweroff
    device_id: -1
  Radio Luisteren DAB+:
    name: '41379771'
    device_id: '65398893'
    player_name: media_player.room1
    volume_device_id: '65398893'
    Button1:
      name: MCh
      command: ModeMultiChStereo
      tooltip: Multichannel Stereo
    Button2:
      name: MCh
      command: ModeMultiChStereo
      tooltip: Multichannel Stereo
    Button3:
      name: MCh
      command: ModeMultiChStereo
      tooltip: Multichannel Stereo
    Button4:
      name: MCh
      command: ModeMultiChStereo
      tooltip: Multichannel Stereo
dimensions:
  scale: '1.17'
  border_width: 2px

**Comment by dezihh** [comment]
Hi,
In my opinion it could just be an indentation problem, or a problem with the name of the activity (Luisteren DAB+). Maybe it's because of the "+". 
Another note: I have completely avoided using quotation marks in my test so far, but I can see them in yours...
Unfortunately I don't see the indentations in your post.
Please try to provide PowerOff with buttons. This doesn't make any sense, but it's great for testing.
Please modify PowerOff for testing as follows:
```
`  
type: custom:my-harmony-card
name: Harmony
entity: remote.woonkamer
tooltip: true
activities:
  PowerOff:
    device_id: -1
    Button1:
      name: Tri
      command: Triangle`
```

**Comment by ArnolddeBolster** [comment]
Hi,

I tried following and the buttons 1-4 appear:
type: custom:my-harmony-card
name: Harmony
entity: remote.woonkamer
tooltip: true
activities:
  PowerOff:
    device_id: -1
    Button1:
      name: Tri
      command: Triangle
    Button2:
      name: Tri
      command: Triangle
    Button3:
      name: Tri
      command: Triangle
    Button4:
      name: Tri
    command: Triangle
  TV kijken:
    name: 36824865
    device_id: 59107742
  Radio luisteren DAB:
    name: 41379771
    device_id: 65398893
    volume_device_id: 65398893
dimensions:
  scale: '1.17'
  border_width: 2px

But when I place the buttons under an activity they do not show up.
And all other buttons do no react when activity is active.
I tried both device and name with and without quotes

This is my harmony config:
{
    "Activities": {
        "-1": "PowerOff",
        "41379770": "TV kijken",
        "41379771": "Radio luisteren DAB+",
        "41379772": "Film kijken",
        "41379773": "CD luisteren",
        "41391085": "TV kijken met Yamaha",
        "42260193": "Game spelen",
        "42745935": "Radio luisteren FM",
        "43349941": "Radio luisteren NET",
        "51907688": "Dyson AM07",
        "52050954": "Pc kijken"
    },
    "Devices": {
        "DUTCH ORIGINALS B09PVKQM6Z": {
            "commands": [
                "PowerOff",
                "PowerOn",
                "PowerToggle",
                "-",
                "+",
                "Dag / Nacht",
                "DirectionDown",
                "DirectionUp",
                "InputAnalog",
                "InputBluetooth",
                "InputOptical1",
                "ModeMovie",
                "ModeMusic",
                "Mute",
                "NextTrack",
                "Pause",
                "Play",
                "PreviousTrack",
                "Roteren",
                "Source",
                "Temperatuur",
                "Timer",
                "Vlammen",
                "VolumeDown",
                "VolumeUp"
            ],
            "id": "78238817"
        },
        "Dyson ventilator": {
            "commands": [
                "PowerToggle",
                "FanSpeedDown",
                "FanSpeedUp",
                "Oscillate",
                "TimerDown",
                "TimerUp"
            ],
            "id": "65398898"
        },
        "Google Mediaspeler": {
            "commands": [
                "PowerOff",
                "PowerOn",
                "Mute",
                "VolumeDown",
                "VolumeUp",
                "DirectionDown",
                "DirectionLeft",
                "DirectionRight",
                "DirectionUp",
                "Select",
                "Stop",
                "Play",
                "Rewind",
                "Pause",
                "FastForward",
                "PreviousTrack",
                "NextTrack",
                "Back",
                "Home"
            ],
            "id": "80212822"
        },
        "Tv Samsung": {
            "commands": [
                "PowerOff",
                "PowerOn",
                "PowerToggle",
                "0",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "Mute",
                "VolumeDown",
                "VolumeUp",
                "ChannelPrev",
                "ChannelDown",
                "ChannelUp",
                "DirectionDown",
                "DirectionLeft",
                "DirectionRight",
                "DirectionUp",
                "Select",
                "Stop",
                "Play",
                "Rewind",
                "Pause",
                "FastForward",
                "Record",
                "Return",
                "Menu",
                "Subtitle",
                "Teletext",
                "TeletextSize",
                "C",
                "B",
                "D",
                "A",
                "Green",
                "Red",
                "Blue",
                "Yellow",
                "Guide",
                "Info",
                "Exit",
                "Aspect",
                "3D",
                "AD",
                "Camera",
                "ChannelList",
                "Content",
                "InputAv",
                "InputComponent",
                "InputExt1",
                "InputExt2",
                "InputHdmi1",
                "InputHdmi2",
                "InputHdmi3",
                "InputHdmi4",
                "InputPc",
                "InputTv",
                "InputUsb",
                "Internet",
                "Media.P",
                "Source",
                "TeletextCancel",
                "TeletextHold",
                "TeletextIndex",
                "TeletextMode",
                "TeletextNextPage",
                "TeletextPreviousPage",
                "TeletextReveal",
                "TeletextStore",
                "TeletextSubPage",
                "Tools",
                "Yamaha_HDMI2"
            ],
            "id": "65398894"
        },
        "Windows-computer": {
            "commands": [
                "+",
                "0",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "Mute",
                "VolumeDown",
                "VolumeUp",
                "ChannelDown",
                "ChannelUp",
                "DirectionDown",
                "DirectionLeft",
                "DirectionRight",
                "DirectionUp",
                "OK",
                "Stop",
                "Play",
                "Rewind",
                "Pause",
                "FastForward",
                "Record",
                "SkipBack",
                "SkipForward",
                "Subtitles",
                "AudioLanguage",
                "Back",
                "C",
                "B",
                "D",
                "A",
                "RecordedTV",
                "MediaCenter",
                "Music",
                "Radio",
                "Video",
                "Guide",
                "PageDown",
                "PageUp",
                "Aspect",
                "Delete",
                "1st pinned to taskbar",
                "2nd pinned to taskbar",
                "3rd pinned to taskbar",
                "a.",
                "Alt",
                "Alt+Enter",
                "Alt+F4",
                "Alt+Shift+Tab",
                "Alt+Tab",
                "b.",
                "Break",
                "c.",
                "CloseProgram",
                "Ctrl",
                "Ctrl+A",
                "Ctrl+Alt+0",
                "Ctrl+Alt+1",
                "Ctrl+Alt+2",
                "Ctrl+Alt+3",
                "Ctrl+Alt+4",
                "Ctrl+Alt+5",
                "Ctrl+Alt+6",
                "Ctrl+Alt+7",
                "Ctrl+Alt+8",
                "Ctrl+Alt+9",
                "Ctrl+C",
                "Ctrl+D",
                "Ctrl+E",
                "Ctrl+F",
                "Ctrl+G",
                "Ctrl+I",
                "Ctrl+M",
                "Ctrl+O",
                "Ctrl+Shift+A",
                "Ctrl+Shift+M",
                "Ctrl+Shift+P",
                "Ctrl+Shift+T",
                "Ctrl+U",
                "Ctrl+V",
                "Ctrl+X",
                "d.",
                "E",
                "e.",
                "End",
                "Enter",
                "Escape",
                "F",
                "f.",
                "F1",
                "F10",
                "F11",
                "F12",
                "F2",
                "F3",
                "F4",
                "F5",
                "F6",
                "F7",
                "F8",
                "F9",
                "FullScreen",
                "G",
                "g.",
                "H",
                "h.",
                "Home",
                "I",
                "i.",
                "J",
                "j.",
                "K",
                "k.",
                "L",
                "l.",
                "LiveTV",
                "LockPC",
                "M",
                "m.",
                "MaximizeWindow",
                "MinimizeWindow",
                "Movies",
                "N",
                "n.",
                "O",
                "o.",
                "P",
                "p.",
                "PlaySlideShow",
                "Q",
                "q.",
                "R",
                "r.",
                "RightClick",
                "S",
                "s.",
                "Search",
                "Shift+Tab",
                "Space",
                "StopSlideShow",
                "T",
                "t.",
                "Tab",
                "U",
                "u.",
                "V",
                "v.",
                "W",
                "w.",
                "WakeUp",
                "Win+4",
                "Win+5",
                "Win+6",
                "Win+7",
                "Win+8",
                "Win+9",
                "Win+Alt+Enter",
                "Win+D",
                "Win+Q",
                "Win+X",
                "Windows",
                "X",
                "x.",
                "Y",
                "y.",
                "Z",
                "z.",
                "ZoomIn",
                "ZoomOut"
            ],
            "id": "69207670"
        },
        "Yamaha AV Receiver": {
            "commands": [
                "PowerOff",
                "PowerOn",
                "PowerToggle",
                "Mute",
                "VolumeDown",
                "VolumeUp",
                "DirectionDown",
                "DirectionLeft",
                "DirectionRight",
                "DirectionUp",
                "Enter",
                "Stop",
                "Play",
                "Rewind",
                "Pause",
                "FastForward",
                "PreviousTrack",
                "NextTrack",
                "Return",
                "TopMenu",
                "PresetPrev",
                "TuneDown",
                "TuneUp",
                "PresetNext",
                "Setup",
                "Sleep",
                "Green",
                "Red",
                "Blue",
                "Yellow",
                "Display",
                "AdaptiveDRCOff",
                "AdaptiveDRCOn",
                "Direct",
                "DspPureDirect",
                "DspStraight",
                "DspSurDecode",
                "Enhancer",
                "Home",
                "InputAirplay",
                "InputAudio1",
                "InputAudio2",
                "InputAudio3",
                "InputAux",
                "InputAv1",
                "InputAv2",
                "InputAv3",
                "InputBluetooth",
                "InputDab",
                "InputFm",
                "InputHdmi1",
                "InputHdmi2",
                "InputHdmi3",
                "InputHdmi4",
                "InputNet",
                "InputNetRadio",
                "InputPandora",
                "InputServer",
                "InputSiriusXM",
                "InputSpotify",
                "InputTuner",
                "InputUsb",
                "Memory",
                "Option",
                "Party",
                "PopUpMenu",
                "ProgramDown",
                "ProgramUp",
                "SceneBdDvd",
                "SceneNet",
                "SceneRadio",
                "SceneTv",
                "SpeakerA",
                "SpeakerB",
                "Straight"
            ],
            "id": "65398893"
        },
        "Yamaha BD Speler": {
            "commands": [
                "PowerToggle",
                "0",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "Clear",
                "DirectionDown",
                "DirectionLeft",
                "DirectionRight",
                "DirectionUp",
                "Enter",
                "Stop",
                "Play",
                "Rewind",
                "Eject",
                "Pause",
                "FastForward",
                "SkipBack",
                "SkipForward",
                "Return",
                "TopMenu",
                "Menu",
                "Subtitle",
                "Audio",
                "Angle",
                "RepeatA-B",
                "Search",
                "PIP",
                "Green",
                "Red",
                "Blue",
                "Yellow",
                "OnScreen",
                "2ndAudio",
                "CDMode",
                "Home",
                "Miracast",
                "PopUp"
            ],
            "id": "65398895"
        },
        "Ziggo Next": {
            "commands": [
                "PowerToggle",
                "0",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "Mute",
                "VolumeDown",
                "VolumeUp",
                "ChannelPrev",
                "ChannelDown",
                "ChannelUp",
                "DirectionDown",
                "DirectionLeft",
                "DirectionRight",
                "DirectionUp",
                "Select",
                "Stop",
                "Play",
                "Rewind",
                "Pause",
                "FastForward",
                "Record",
                "Menu",
                "Back",
                "Teletext",
                "DVR",
                "Green",
                "Red",
                "Blue",
                "Yellow",
                "Guide",
                "Info",
                "Exit",
                "Help",
                "OnDemand"
            ],
            "id": "65398896"
        }
    }
}
________________________________
Van: dezihh ***@***.***>
Verzonden: zondag 16 juni 2024 15:09
Aan: dezihh/my-harmony-card ***@***.***>
CC: olybol ***@***.***>; Author ***@***.***>
Onderwerp: Re: [dezihh/my-harmony-card] Wrong device saved ? and buttons do not appear /react (Issue #2)


Hi,
In my opinion it could just be an indentation problem, or a problem with the name of the activity (Luisteren DAB+). Maybe it's because of the "+".
Another note: I have completely avoided using quotation marks in my test so far, but I can see them in yours...
Unfortunately I don't see the indentations in your post.
Please try to provide PowerOff with buttons. This doesn't make any sense, but it's great for testing.
Please modify PowerOff for testing as follows:

`
type: custom:my-harmony-card
name: Harmony
entity: remote.woonkamer
tooltip: true
activities:
  PowerOff:
    device_id: -1
    Button1:
      name: Tri
      command: Triangle`

**Comment by dezihh** [comment]
Hi,It makes sense to me. You have to use exactly the name as it is written in harmony.conf. This is relevant, not the device_id, name, etc.  Please double check and if possible, please rename one activity of your harmony setup to a simple name, maybe this works. I am sure, that there is a naming problem. The compare between name of active activity to the name reported by harmony does not match.  Why ever. Here you will find the problem, I am sure.  Maybe an additional hint: Please have a look to  the entities in Developer tools. There you should find remote.woonkamer. In the attributes of this entety, there you will find all activities.  Do copy and paste one of the listed activities to your card.  Maybe this works. Please reply, we will bring it to a good end ;-]Am 16.06.2024 um 18:27 schrieb olybol ***@***.***>:﻿
Hi,



I tried following and the buttons 1-4 appear:

type: custom:my-harmony-card

name: Harmony

entity: remote.woonkamer

tooltip: true

activities:

  PowerOff:

    device_id: -1

    Button1:

      name: Tri

      command: Triangle

    Button2:

      name: Tri

      command: Triangle

    Button3:

      name: Tri

      command: Triangle

    Button4:

      name: Tri

    command: Triangle

  TV kijken:

    name: 36824865

    device_id: 59107742

  Radio luisteren DAB:

    name: 41379771

    device_id: 65398893

    volume_device_id: 65398893

dimensions:

  scale: '1.17'

  border_width: 2px



But when I place the buttons under an activity they do not show up.

And all other buttons do no react when activity is active.

I tried both device and name with and without quotes



This is my harmony config:

{

    "Activities": {

        "-1": "PowerOff",

        "41379770": "TV kijken",

        "41379771": "Radio luisteren DAB+",

        "41379772": "Film kijken",

        "41379773": "CD luisteren",

        "41391085": "TV kijken met Yamaha",

        "42260193": "Game spelen",

        "42745935": "Radio luisteren FM",

        "43349941": "Radio luisteren NET",

        "51907688": "Dyson AM07",

        "52050954": "Pc kijken"

    },

    "Devices": {

        "DUTCH ORIGINALS B09PVKQM6Z": {

            "commands": [

                "PowerOff",

                "PowerOn",

                "PowerToggle",

                "-",

                "+",

                "Dag / Nacht",

                "DirectionDown",

                "DirectionUp",

                "InputAnalog",

                "InputBluetooth",

                "InputOptical1",

                "ModeMovie",

                "ModeMusic",

                "Mute",

                "NextTrack",

                "Pause",

                "Play",

                "PreviousTrack",

                "Roteren",

                "Source",

                "Temperatuur",

                "Timer",

                "Vlammen",

                "VolumeDown",

                "VolumeUp"

            ],

            "id": "78238817"

        },

        "Dyson ventilator": {

            "commands": [

                "PowerToggle",

                "FanSpeedDown",

                "FanSpeedUp",

                "Oscillate",

                "TimerDown",

                "TimerUp"

            ],

            "id": "65398898"

        },

        "Google Mediaspeler": {

            "commands": [

                "PowerOff",

                "PowerOn",

                "Mute",

                "VolumeDown",

                "VolumeUp",

                "DirectionDown",

                "DirectionLeft",

                "DirectionRight",

                "DirectionUp",

                "Select",

                "Stop",

                "Play",

                "Rewind",

                "Pause",

                "FastForward",

                "PreviousTrack",

                "NextTrack",

                "Back",

                "Home"

            ],

            "id": "80212822"

        },

        "Tv Samsung": {

            "commands": [

                "PowerOff",

                "PowerOn",

                "PowerToggle",

                "0",

                "1",

                "2",

                "3",

                "4",

                "5",

                "6",

                "7",

                "8",

                "9",

                "Mute",

                "VolumeDown",

                "VolumeUp",

                "ChannelPrev",

                "ChannelDown",

                "ChannelUp",

                "DirectionDown",

                "DirectionLeft",

                "DirectionRight",

                "DirectionUp",

                "Select",

                "Stop",

                "Play",

                "Rewind",

                "Pause",

                "FastForward",

                "Record",

                "Return",

                "Menu",

                "Subtitle",

                "Teletext",

                "TeletextSize",

                "C",

                "B",

                "D",

                "A",

                "Green",

                "Red",

                "Blue",

                "Yellow",

                "Guide",

                "Info",

                "Exit",

                "Aspect",

                "3D",

                "AD",

                "Camera",

                "ChannelList",

                "Content",

                "InputAv",

                "InputComponent",

                "InputExt1",

                "InputExt2",

                "InputHdmi1",

                "InputHdmi2",

                "InputHdmi3",

                "InputHdmi4",

                "InputPc",

                "InputTv",

                "InputUsb",

                "Internet",

                "Media.P",

                "Source",

                "TeletextCancel",

                "TeletextHold",

                "TeletextIndex",

                "TeletextMode",

                "TeletextNextPage",

                "TeletextPreviousPage",

                "TeletextReveal",

                "TeletextStore",

                "TeletextSubPage",

                "Tools",

                "Yamaha_HDMI2"

            ],

            "id": "65398894"

        },

        "Windows-computer": {

            "commands": [

                "+",

                "0",

                "1",

                "2",

                "3",

                "4",

                "5",

                "6",

                "7",

                "8",

                "9",

                "Mute",

                "VolumeDown",

                "VolumeUp",

                "ChannelDown",

                "ChannelUp",

                "DirectionDown",

                "DirectionLeft",

                "DirectionRight",

                "DirectionUp",

                "OK",

                "Stop",

                "Play",

                "Rewind",

                "Pause",

                "FastForward",

                "Record",

                "SkipBack",

                "SkipForward",

                "Subtitles",

                "AudioLanguage",

                "Back",

                "C",

                "B",

                "D",

                "A",

                "RecordedTV",

                "MediaCenter",

                "Music",

                "Radio",

                "Video",

                "Guide",

                "PageDown",

                "PageUp",

                "Aspect",

                "Delete",

                "1st pinned to taskbar",

                "2nd pinned to taskbar",

                "3rd pinned to taskbar",

                "a.",

                "Alt",

                "Alt+Enter",

                "Alt+F4",

                "Alt+Shift+Tab",

                "Alt+Tab",

                "b.",

                "Break",

                "c.",

                "CloseProgram",

                "Ctrl",

                "Ctrl+A",

                "Ctrl+Alt+0",

                "Ctrl+Alt+1",

                "Ctrl+Alt+2",

                "Ctrl+Alt+3",

                "Ctrl+Alt+4",

                "Ctrl+Alt+5",

                "Ctrl+Alt+6",

                "Ctrl+Alt+7",

                "Ctrl+Alt+8",

                "Ctrl+Alt+9",

                "Ctrl+C",

                "Ctrl+D",

                "Ctrl+E",

                "Ctrl+F",

                "Ctrl+G",

                "Ctrl+I",

                "Ctrl+M",

                "Ctrl+O",

                "Ctrl+Shift+A",

                "Ctrl+Shift+M",

                "Ctrl+Shift+P",

                "Ctrl+Shift+T",

                "Ctrl+U",

                "Ctrl+V",

                "Ctrl+X",

                "d.",

                "E",

                "e.",

                "End",

                "Enter",

                "Escape",

                "F",

                "f.",

                "F1",

                "F10",

                "F11",

                "F12",

                "F2",

                "F3",

                "F4",

                "F5",

                "F6",

                "F7",

                "F8",

                "F9",

                "FullScreen",

                "G",

                "g.",

                "H",

                "h.",

                "Home",

                "I",

                "i.",

                "J",

                "j.",

                "K",

                "k.",

                "L",

                "l.",

                "LiveTV",

                "LockPC",

                "M",

                "m.",

                "MaximizeWindow",

                "MinimizeWindow",

                "Movies",

                "N",

                "n.",

                "O",

                "o.",

                "P",

                "p.",

                "PlaySlideShow",

                "Q",

                "q.",

                "R",

                "r.",

                "RightClick",

                "S",

                "s.",

                "Search",

                "Shift+Tab",

                "Space",

                "StopSlideShow",

                "T",

                "t.",

                "Tab",

                "U",

                "u.",

                "V",

                "v.",

                "W",

                "w.",

                "WakeUp",

                "Win+4",

                "Win+5",

                "Win+6",

                "Win+7",

                "Win+8",

                "Win+9",

                "Win+Alt+Enter",

                "Win+D",

                "Win+Q",

                "Win+X",

                "Windows",

                "X",

                "x.",

                "Y",

                "y.",

                "Z",

                "z.",

                "ZoomIn",

                "ZoomOut"

            ],

            "id": "69207670"

        },

        "Yamaha AV Receiver": {

            "commands": [

                "PowerOff",

                "PowerOn",

                "PowerToggle",

                "Mute",

                "VolumeDown",

                "VolumeUp",

                "DirectionDown",

                "DirectionLeft",

                "DirectionRight",

                "DirectionUp",

                "Enter",

                "Stop",

                "Play",

                "Rewind",

                "Pause",

                "FastForward",

                "PreviousTrack",

                "NextTrack",

                "Return",

                "TopMenu",

                "PresetPrev",

                "TuneDown",

                "TuneUp",

                "PresetNext",

                "Setup",

                "Sleep",

                "Green",

                "Red",

                "Blue",

                "Yellow",

                "Display",

                "AdaptiveDRCOff",

                "AdaptiveDRCOn",

                "Direct",

                "DspPureDirect",

                "DspStraight",

                "DspSurDecode",

                "Enhancer",

                "Home",

                "InputAirplay",

                "InputAudio1",

                "InputAudio2",

                "InputAudio3",

                "InputAux",

                "InputAv1",

                "InputAv2",

                "InputAv3",

                "InputBluetooth",

                "InputDab",

                "InputFm",

                "InputHdmi1",

                "InputHdmi2",

                "InputHdmi3",

                "InputHdmi4",

                "InputNet",

                "InputNetRadio",

                "InputPandora",

                "InputServer",

                "InputSiriusXM",

                "InputSpotify",

                "InputTuner",

                "InputUsb",

                "Memory",

                "Option",

                "Party",

                "PopUpMenu",

                "ProgramDown",

                "ProgramUp",

                "SceneBdDvd",

                "SceneNet",

                "SceneRadio",

                "SceneTv",

                "SpeakerA",

                "SpeakerB",

                "Straight"

            ],

            "id": "65398893"

        },

        "Yamaha BD Speler": {

            "commands": [

                "PowerToggle",

                "0",

                "1",

                "2",

                "3",

                "4",

                "5",

                "6",

                "7",

                "8",

                "9",

                "Clear",

                "DirectionDown",

                "DirectionLeft",

                "DirectionRight",

                "DirectionUp",

                "Enter",

                "Stop",

                "Play",

                "Rewind",

                "Eject",

                "Pause",

                "FastForward",

                "SkipBack",

                "SkipForward",

                "Return",

                "TopMenu",

                "Menu",

                "Subtitle",

                "Audio",

                "Angle",

                "RepeatA-B",

                "Search",

                "PIP",

                "Green",

                "Red",

                "Blue",

                "Yellow",

                "OnScreen",

                "2ndAudio",

                "CDMode",

                "Home",

                "Miracast",

                "PopUp"

            ],

            "id": "65398895"

        },

        "Ziggo Next": {

            "commands": [

                "PowerToggle",

                "0",

                "1",

                "2",

                "3",

                "4",

                "5",

                "6",

                "7",

                "8",

                "9",

                "Mute",

                "VolumeDown",

                "VolumeUp",

                "ChannelPrev",

                "ChannelDown",

                "ChannelUp",

                "DirectionDown",

                "DirectionLeft",

                "DirectionRight",

                "DirectionUp",

                "Select",

                "Stop",

                "Play",

                "Rewind",

                "Pause",

                "FastForward",

                "Record",

                "Menu",

                "Back",

                "Teletext",

                "DVR",

                "Green",

                "Red",

                "Blue",

                "Yellow",

                "Guide",

                "Info",

                "Exit",

                "Help",

                "OnDemand"

            ],

            "id": "65398896"

        }

    }

}

________________________________

Van: dezihh ***@***.***>

Verzonden: zondag 16 juni 2024 15:09

Aan: dezihh/my-harmony-card ***@***.***>

CC: olybol ***@***.***>; Author ***@***.***>

Onderwerp: Re: [dezihh/my-harmony-card] Wrong device saved ? and buttons do not appear /react (Issue #2)





Hi,

In my opinion it could just be an indentation problem, or a problem with the name of the activity (Luisteren DAB+). Maybe it's because of the "+".

Another note: I have completely avoided using quotation marks in my test so far, but I can see them in yours...

Unfortunately I don't see the indentations in your post.

Please try to provide PowerOff with buttons. This doesn't make any sense, but it's great for testing.

Please modify PowerOff for testing as follows:



`

type: custom:my-harmony-card

name: Harmony

entity: remote.woonkamer

tooltip: true

activities:

  PowerOff:

    device_id: -1

    Button1:

      name: Tri

      command: Triangle`

**Comment by ArnolddeBolster** [comment]
I tried the options you proposed and finally I managed to see the buttons 1-4 and some functions Volume etc (except Home) are working. I have not tested functionality of buttons 1-4 yet. 
![image](https://github.com/dezihh/my-harmony-card/assets/71195708/4874b0c3-3766-4f11-9685-c380454da434)

As you can see the visualisation left is gone after adding extra code. I tried several alligments of the code but then buttons dissapear again.

activities:
  PowerOff:
    name: Poweroff
    Button1:
        name: MNU
        command: Menu
    device_id: -1
  Radio luisteren DAB:
    name: '41379771'
    device_id: '65398893'
  TV kijken:
    name: '41379770'
    device_id: '65398896'
dimensions:
  scale: '1.01'
  border_width: 2px
colors:
  background: '#f7f7f7'

The quotes on name and device_id appaer when code editor is openend in visual editor its without quotes

**Comment by dezihh** [comment]
Hi,
What you say makes sense! 
The point is, that the part of the activity from your config of the card is addressed that corresponds _exactly_ to the name of the activity. The numbers are not used, the name (Headline) is used. Of course, no other commands work next to the button because there is a mismatch between the configured and the actual name. 
I have 2 suggestions:

1. Please rename an action in your Harmony and give it a simple name (e.g. ABC, Radio,...)
Test if that works

2. Go to the developer tools and go to the states of remote.woonkamer. There in the attributes, on the right in the table, you will find the configured activities of remote.woonkamer. Copy one out and use it for testing. The idea: If there are non-printable characters, we simply copy and paste them into the configuration.

Please let us know if you were successful :-)

PS: Please use the "<>" button above for posting code, then I can see the indentation too ;-)

**Comment by dezihh** [comment]
Good to hear, things are progressing... :-)
Not all devices have a “Home” command. 
Please check again in harmony.conf whether the device with device_id 65398896 provides "Home" as function. If the other commands work, I suspect not. However, you can map the home button to another function if necessary.
I can't say from here why the visualization disappears.
If you like, please send me the entire configuration of the card, I'll be happy to check it. Please be sure to use the "<>" button at the top of Github editor to post the configuration. If you highlight your code and then press this key, the code will be interpreted as a code and should appear to me with indentation. This is important, otherwise I can't check...

**Comment by dezihh** [comment]
I see, the device_id 6539889 "Ziggo Next" is already posted above. It has no Home function, as suspected by me ....

**Comment by ArnolddeBolster** [comment]
I'm sorry but removed this integration.
It's not working for me nevertheless it looks promising
