### ISSUE TITLE
Feature request: ButtonA-B also optional for each activity

### ISSUE THREAD

**Issue by ArnolddeBolster** [dezihh/my-harmony-card#20]
My initial request for an extra button row was meant for extra optional comman buttons for each activity.
e.g with activity watch television I need 2 rows ( 4 buttons for streaming services like Netflix, Disney+, ViaPlay etc and 4 for services like Teletext, DVR, OnDemand etc.)
![image](https://github.com/user-attachments/assets/013c7055-6850-4f83-bd06-e5f4d9280ab4)

but never thought of a button row for extra features to control bulbs, plugs, TV etc.

so i am a bit struggling with the new feature to control extra devices which are also available on my harmony remote (2 buttons for bulbs with +- button for dimming and 2 buttons for 2 plugs or group of plugs. I now use the bulb button for my group lights with dimming option) 

Maybe I'm going to call service for popup to controle group bulb and each individual bulb.
Then it would also be nice if a color change of the button would be possible

what do you think ?

**Comment by dezihh** [comment]
:-D yes, you are right, at least in the straight forward way :-) I use these buttons for e.g. for switching the sound mode of my av receiver, beacause nearly every activity is needing this. Other buttons I use to switch on or off a specific devices.

What you can do as well is to create a script, find out witch activity is currently running and send some specific action for this activity...
Btw: I recommend pyscript. In my opinion much better than the yaml based automation ha offers....

**Comment by ArnolddeBolster** [comment]
well, these ButtonsA-D are very useful for me. I can run setup for my receiver (Button4) while activity listen to radio is running. Ans I can seperately use ButtonA to switch on TV, ButtonB to selct the right hdmi channel and setup page from my receiver is available. ButtonC I use for a specific plug and ButtonD for a light group. These buttons need always to be on top.

It would be nice if the row order of buttonsA-D and Buttons1-4 could be changed.

And for me it would be very useful if an extra buttonrow Button5-8 would be available for within an activity to be able to use extra commands for some devices.

But I'm very happy with the changes sofar !!!

**Comment by ArnolddeBolster** [comment]
Maybe more on top is a better place for ButtonA-B ?
![image](https://github.com/user-attachments/assets/f90f289c-f726-4b60-b9e2-9c1b5a532e11)

**Comment by ArnolddeBolster** [comment]
I made a small change in ButtonA-D and added a service call for popup to get device buttons from my harmony remote which aren't defined in the remote and it works !!!!
many thanks for all your effort and for me it would be great if the ButtonA-D get another position as proposed.
![image](https://github.com/user-attachments/assets/04702ddc-4cb8-4f6b-a549-bc80149d676b)

**Comment by dezihh** [comment]
Maybe I do not understand, but the global buttons are now at the top. What is missing?
![Global-button](https://github.com/user-attachments/assets/8af717fe-176b-484b-9261-aa65a249a446)

**Comment by ArnolddeBolster** [comment]
The global button on top are very nice, but what I meant was infact an extra optional buttonrow (duplicate from Button1-4) for some devices behind the activity need more than 4 feature buttons.

But I can live with the way it is now. It very usefull and I am very happy with it  !!!!!

**Comment by dezihh** [comment]
*o, I assume, you have not read the release notes?
Are you aware, that there are now Button[1-8]?!

**Comment by ArnolddeBolster** [comment]
sorry I wasn't aware of it because I thought only the place of the row was changed.
I changed it and it works perfectly !!!

many many thanks !!
