### ISSUE TITLE
commands do not work properly

### ISSUE THREAD

**Issue by ArnolddeBolster** [dezihh/my-harmony-card#21]
When using the commands for Netflix, Disney+, ViaPlay and PrimeVideo nothing happens while in madmacio's it's working properly.
This is the code used:
    Button1:
      name: Netflix
      icon: mdi:netflix
      command: netflix
      tooltip: Netflix
    Button2:
      name: Disney+
      icon: phu:disney-plus
      command: disney+
      tooltip: Disney+
    Button3:
      name: Prime
      icon: si:amazonaws
      command: Amazonprime
      tooltip: Amazon Prime
    Button4:
      name: Viaplay
      icon: si:v
      command: Viaplay
      tooltip: Viaplay

And this is working in madmacio's:
          sources:
            - name: Netflix
              icon: mdi:netflix
            - name: Disney+
              icon: disney
            - name: Prime Video
              icon: si:amazonaws
            - name: Viaplay info
              icon: si:v

**Comment by dezihh** [comment]
Not a surprise to me. You can send every command to the device, you find in the harmony.conf. There you will find no Netflix, so this can not work. 
You have to switch the button to work with service calls. The you can make a service call to your device and open whatever you like, or am i wrong?

**Comment by ArnolddeBolster** [comment]
I hope I can make a service call, I found out it is in fact an attribute in my mediabox:
![image](https://github.com/user-attachments/assets/c97389dd-aa9a-4781-b508-b88f72f3b575)

**Comment by ArnolddeBolster** [comment]
I managed to make a proper call so its solved
