### ISSUE TITLE
Not all devices use the same command on some buttons

### ISSUE THREAD

**Issue by ArnolddeBolster** [dezihh/my-harmony-card#22]
Some buttons do not work properly within their activity.
![image](https://github.com/user-attachments/assets/b57ab90b-2379-40df-bef5-c52bdae48f22)
e.g. the OK works properly using activity with watching TV (gues select)
but doesn't work with listen to radio (Enter)

![image](https://github.com/user-attachments/assets/c5fc8c7a-9000-43ff-b735-374c5bb2a680)
within activity watching TV it works (Back ?)
and within activity listen to radio (Return)

Hopefully some buttons can be programmed to set the right command within the activity

**Comment by ArnolddeBolster** [comment]
I tried to make a mapping of my devices. green marked are tested and working (watching tv with my setup box)
you can see the differences of commands used by the devices

[Mapping.xlsx](https://github.com/user-attachments/files/16968666/Mapping.xlsx)

**Comment by dezihh** [comment]
Not sure if I understand right. 
You can easy remap e.g. OK button to whatever you like, as described in [activities] (https://github.com/dezihh/my-harmony-card#activities-options) chapter

**Comment by ArnolddeBolster** [comment]
ok I understand
but could you make the return button also available to work that way ?

**Comment by dezihh** [comment]
I assume, it should work, but indeed ist is not documented. Please try a remapping for "Back" in the same way like "ok", "info", etc....

**Comment by ArnolddeBolster** [comment]
you're great, it works
