### ISSUE TITLE
Left button not working

### ISSUE THREAD

**Issue by andrevidigal01** [dezihh/my-harmony-card#23]
The left button is not working accross all activities/devices:

![image](https://github.com/user-attachments/assets/d32d0ed8-3c7d-4e1a-bd5b-ab49667e9acc)

**Comment by dezihh** [comment]
You are Right! It is sending Left instead of DirectionLeft. 
I'll fix it the next days....

**Comment by dezihh** [comment]
Should be fixed with 1.40.1,, please test
