### ISSUE TITLE
OK Button not wotking on Samsung Smart TV

### ISSUE THREAD

**Issue by Man-in-Black** [dezihh/my-harmony-card#24]
**Describe the bug**
I love your remote and I'm using it nearly for every device now. But I didn't get the OK Button to work with my Samsung Smart TV.

**To Reproduce**
1. Start the TV
2. Navigate to any button
3. Try to click "OK"

**Expected behavior**
When the OK button is pressed the selected action should start.

I hope this describes it well.

Would be happy if you have a suggestion.
I've tried nearly everything: "OK", "Enter", "Return", "Go", ....

Best regards
Man-in-Black

**Comment by dezihh** [comment]
Hi Sascha,

I assume, that your harmony Remote Control itself is working properly? Next step please have a look inside of the harmony???.conf. Look for your samsung and see, if there is a „ok“ as command reported. Find the correct expression for ok and map it on the ok button. 
If you like to go deeper, you can enable debugging in the configuration and you can see which keycodes are sent to your Samsung   

If you need more assistance feel free to ask :-)

**Comment by Man-in-Black** [comment]
Thanks a lot, correct button was "Select" :-D
I'll close this off, thanks for your fast help ;-)
