### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by ArnolddeBolster** [dezihh/my-harmony-card#4]
Hi,

I gave it another try and reinstalled it and compared the my-harmony-card with the madmicio's one.
The advantage for me using your card is that most of the buttons already contain the action belonging to the activity and for madmicio's remote I had to write several scripts for the action. Nevertheless it has the abillty to override buttons and offer some more flexibility in that way.
The great disadvatnage of madmicio's remote is there is only 1 workin buttonrow and hope you are able to offer more in future.

Here my resultsof testing
I would like to have same color settings like madmacio has.
The OK and Up button didn't work for me with setupbox (TV kijken)
Volume down does the same as volumeup with TV kijken
I would like to have an optons to use icons for the extra buttonsrow(s)
![image](https://github.com/dezihh/my-harmony-card/assets/71195708/d359e92d-4535-428b-a9ee-4b1a0b995ac9)

On the remote underneath I also have upperleft a button with a popup card with all my favorite TV channels and have such button also (not in this remote) for radio stations as well
![image](https://github.com/dezihh/my-harmony-card/assets/71195708/287b840c-4c8d-4b5c-b091-d12b9755ba0b)

I hope this all helps or is possible for future enhancements

keep up the good work !!!

My madmicio's remote:
![image](https://github.com/dezihh/my-harmony-card/assets/71195708/0efc517e-4e1f-4784-b0cc-ba165ee92e1e)

colorscheme i used:
 colors:
            active-background-button-color: '#0080ff'
            deactive-background-button-color: '#f2f0fa'
            button-border-standard: rgba(0, 128, 255, .5)
            state-icon-active-color: '#0080ff'
            buttons: '#363538'
            text: white
            background: black

Extra sources I have on my remote for mediabox
        sources:
            - name: Netflix
              icon: mdi:netflix
            - name: Disney+
              icon: disney
            - name: Prime Video
              icon: si:amazonaws
            - name: Viaplay info
              icon: si:v
            - name: Menu
              icon: mdi:menu
            - name: Teletekst
              icon: mdi:format-text
            - name: TV Guide
              icon: mdi:television-guide
            - name: DVR
              icon: mdi:video

and this is the popup I use for TV channels
![image](https://github.com/dezihh/my-harmony-card/assets/71195708/a51d0547-441c-49be-88ed-080d41cf33c0)

**Comment by dezihh** [comment]
Hi, 
first thank you for your Feedback!

1. More Buttons:
    I thought already about it. My idea: Add a new row  and make it able to give a individual command _and_ a individual device_id too
2. Icons for Buttons:
    Must see how much effort, I will check it when I work on 1.
3. OK Button:
    you can easy remap in the Syntax: ```OK: <new command>``` for each separate activity
4. Up Button
    Actual no remapping possible. Which button do you mean? ChUp or DirectionUp?
5. VolumeUp / Down
    Don't understand. You can switch VolumeUp and Down easily to a different device in your current activity by using volume_device_id
6. PopUp
    Actual no idea how to implement. Madmicio is using for that the BrowserMod Service. I am unhappy with the behavior of the BrowserMod Service in general. Because of that, it is not implemented. To be honest, I thought about during development to implement the media_player as a card. But for the same reason (an I have no different idea to implement) this function was not released.
If somebody else has a good idea how to implement without browsermod, I will think about it. :)

However, if the are still bugs in the card (or doc) I am willing to fix it, new feature will come in autumn or winter, because of my family ;-)

**Comment by ArnolddeBolster** [comment]
Hi,
Your welcome, hopefully it can helps
1. More Buttons:
2.Icons for Buttons:
maybe the code from madmicio could help in the right direction for this works for me properly.
I can share my cardcode how I have configured it to give you an impression
3.OK Button:
gave it a try but no luck sofar with the syntax
4. Up Button
it's the DirectionUp which is not working
5. the VolumeDown does the same as VolumeUp for the mediabox and adressed volume_device_id to the proper deviceid
6. 6. PopUp
I use indeed BrowserMod Service and sofar never had issues The only thing I have configured is using 1 button to get the popup. 

I understand new features are no priority. Family is most important :-)

Here is the code I use with the madmicio to give you an impression:
    card:
      type: vertical-stack
      cards:
        - type: media-control
          entity: media_player.woonkamer_4
        - type: media-control
          entity: media_player.mediabox
        - type: custom:lg-remote-control
          entity: media_player.mediabox
          dimensions: null
          scale: 0.8
          border_width: 2px
          name: ZiggoNext
          colors:
            active-background-button-color: '#0080ff'
            deactive-background-button-color: '#f2f0fa'
            button-border-standard: rgba(0, 128, 255, .5)
            state-icon-active-color: '#0080ff'
            buttons: '#363538'
            text: white
            background: black
          sources:
            - name: Netflix
              icon: mdi:netflix
            - name: Disney+
              icon: disney
            - name: Prime Video
              icon: si:amazonaws
            - name: Viaplay info
              icon: si:v
            - name: Menu
              icon: mdi:menu
            - name: Teletekst
              icon: mdi:format-text
            - name: TV Guide
              icon: mdi:television-guide
            - name: DVR
              icon: mdi:video
          color_buttons: true
          keys:
            '1':
              service: media_player.play_media
              data:
                entity_id: media_player.mediabox
                media_content_id: NPO 1
                media_content_type: app
            '2':
              service: script.mediabox_bronselecteren_npo2
              data:
                entity_id: null
            '3':
              service: script.mediabox_bronselecteren_npo3
              data:
                entity_id: null
            '4':
              service: script.mediabox_bronselecteren_rtl4
              data:
                entity_id: null
            '5':
              service: script.mediabox_bronselecteren_rtl5
              data:
                entity_id: null
            '6':
              service: script.mediabox_bronselecteren_sbs6
              data:
                entity_id: null
            '7':
              service: script.mediabox_bronselecteren_rtl7
              data:
                entity_id: null
            '8':
              service: script.mediabox_bronselecteren_veronica
              data:
                entity_id: null
            '9':
              service: script.mediabox_bronselecteren_net5
              data:
                entity_id: null
            RED:
              service: lghorizon.remote_key_press
              data:
                entity_id: media_player.mediabox
                remote_key: MediaTopMenu
            Menu:
              service: lghorizon.remote_key_press
              data:
                entity_id: media_player.mediabox
                remote_key: Menu
            color_buttons: true
            optional_buttons: true
            GREEN:
              service: lghorizon.remote_key_press
              data:
                entity_id: media_player.mediabox
                remote_key: Teletext
            YELLOW:
              service: lghorizon.remote_key_press
              data:
                entity_id: media_player.mediabox
                remote_key: Guide
            BLUE:
              service: lghorizon.remote_key_press
              data:
                entity_id: media_player.mediabox
                remote_key: DVR
            POWER:
              service: lghorizon.remote_key_press
              data:
                entity_id: media_player.mediabox
                remote_key: Power
            UP:
              service: lghorizon.remote_key_press
              data:
                entity_id: media_player.mediabox
                remote_key: ArrowUp
            DOWN:
              service: lghorizon.remote_key_press
              data:
                entity_id: media_player.mediabox
                remote_key: ArrowDown
            LEFT:
              service: lghorizon.remote_key_press
              data:
                entity_id: media_player.mediabox
                remote_key: ArrowLeft
            RIGHT:
              service: lghorizon.remote_key_press
              data:
                entity_id: media_player.mediabox
                remote_key: ArrowRight
            ENTER:
              service: lghorizon.remote_key_press
              data:
                entity_id: media_player.mediabox
                remote_key: Enter
            BACK:
              service: lghorizon.remote_key_press
              data:
                entity_id: media_player.mediabox
                remote_key: Escape
            EXIT:
              service: lghorizon.remote_key_press
              data:
                entity_id: media_player.mediabox
                remote_key: Exit
            VOLUME_UP:
              service: script.harmony_ziggo_next_volumeup
            VOLUME_DOWN:
              service: script.harmony_ziggo_next_volumedown
            MUTE:
              service: lghorizon.remote_key_press
              data:
                entity_id: media_player.mediabox
                remote_key: Mute
            CHANNELUP:
              service: lghorizon.remote_key_press
              data:
                entity_id: media_player.mediabox
                remote_key: ChannelUp
            CHANNELDOWN:
              service: lghorizon.remote_key_press
              data:
                entity_id: media_player.mediabox
                remote_key: ChannelDown
            HOME:
              service: script.harmony_ziggo_next_menu
              data:
                entity_id: null
            INFO:
              service: lghorizon.remote_key_press
              data:
                entity_id: media_player.mediabox
                remote_key: Info
            PLAY:
              service: lghorizon.remote_key_press
              data:
                entity_id: media_player.mediabox
                remote_key: Play
            PAUSE:
              service: lghorizon.remote_key_press
              data:
                entity_id: media_player.mediabox
                remote_key: Pause
            STOP:
              service: lghorizon.remote_key_press
              data:
                entity_id: media_player.mediabox
                remote_key: Stop
            RECORD:
              service: lghorizon.record
              data:
                entity_id: media_player.mediabox
            REWIND:
              service: lghorizon.rewind
              data:
                entity_id: media_player.mediabox
            FAST_FOWARD:
              service: lghorizon.fast_forward
              data:
                entity_id: media_player.mediabox
          av_receiver_family: yamaha
          ampli_entity: ''
          channels:
            - image: /local/Pictures/npo1.png
              number: '1'
            - image: /local/Pictures/npo2.png
              number: '2'
            - image: /local/Pictures/npo3.png
              number: '3'
            - image: /local/Pictures/rtl4.jpeg
              number: '4'
            - image: /local/Pictures/rtl5.jpeg
              number: '5'
            - image: /local/Pictures/sbs6nw.jpeg
              number: '6'
            - image: /local/Pictures/rtl7.png
              number: '7'
            - image: /local/Pictures/veronica_tv.png
              number: '8'
            - image: /local/Pictures/net5.png
              number: '9'
            - image: /local/Pictures/rtl8.png
              number: '10'
            - image: /local/Pictures/starchannel.png
              number: '11'
            - image: /local/Pictures/ziggosport.png
              number: '12'
            - image: /local/Pictures/comedycentral.png
              number: '13'
            - image: /local/Pictures/sbs9nw.png
              number: '14'
            - image: /local/Pictures/vrt1.png
              number: '15'
            - image: /local/Pictures/vrtcanvas.png
              number: '16'
            - image: /local/Pictures/ketnet.png
              number: '17'
            - image: /local/Pictures/npo1extra.png
              number: '18'
            - image: /local/Pictures/omroepgelderland.png
              number: '19'
            - image: /local/Pictures/omroepwest.png
              number: '20'
            - image: /local/Pictures/espn.png
              number: '21'

**Comment by dezihh** [comment]
Hi,

you are right, there was a mistake inside DirectionUp. Corrected. We'll find it in new Release.
Regarding OK Button, see bottom of Readme. There is described, how to debug, which command is sent if button is pressed. I did a test on my system, I can remap the "OK" button.

For the future, please do me a favor: If you have feature requests, please try to add one request for each issue. Otherwise I will loose overview in the future :-/

Anyway: Thank you for your support and your Ideas

**Comment by ArnolddeBolster** [comment]
could you please help me on this one, I can not get configured the OK button with Enter command
debugging did not give a clue

what wrong with my code:
type: custom:my-harmony-card
name: Harmony
entity: remote.woonkamer
tooltip: true
activities:
  PowerOff:
    name: Poweroff
    device_id: -1
  TV kijken:
    name: '41379770'
    device_id: '65398896'
    player_name: media_player.mediabox
    OK:
      command: Enter
      device_id: '65398896'
    Button1:
      name: MNu
      command: Menu
      tooltip: Menu
    Button2:
      name: Txt
      command: Teletext
      tooltip: Teletext
    Button3:
      name: Gui
      command: Guide
      tooltip: Guide
    Button4:
      name: DVR
      command: DVR
      tooltip: DVR
      volume_device_id: '65398896'
  Radio luisteren DAB:
    name: '41379771'
    device_id: '65398893'
    volume_device_id: '65398893'
    player_name: media_player.room1
    Button1:
      name: prv
      command: PresetPrev
      tooltip: PresetPrev
    Button2:
      name: nxt
      command: PresetNext
      tooltip: PresetNext
    Button3: null
    Button4: null
dimensions:
  scale: '0.99'
  border_width: 2px

**Comment by dezihh** [comment]
Please Try OK: Enter

**Comment by ArnolddeBolster** [comment]
I already tried that without succes.
Strangely enough when I compare it with mamicio's remote the command is the same and works.
            ENTER:
              service: lghorizon.remote_key_press
              data:
                entity_id: media_player.mediabox
                remote_key: Enter

I also refreshed my browser and restarted HAS several times without succes

**Comment by dezihh** [comment]
Normally it can not be. In my installation ist is working. I do not see you indentation, maybe there is something wrong.
Here a part of your config as code. Please check:
````
type: custom:my-harmony-card
name: Harmony
entity: remote.woonkamer
tooltip: true
activities:
    PowerOff:
        name: Poweroff
        device_id: -1
    TV kijken:
        name: '41379770'
        device_id: '65398896'
        player_name: media_player.mediabox
        OK: Enter
        device_id: '65398896'  <-- why they are to device_id for TV kijken?!
        Button1:
            name: MNu`
````

**Comment by ArnolddeBolster** [comment]
device_id was extra attempt to get it worked but changed that with no succes thru:
  TV kijken:
    name: '41379770'
    device_id: '65398896'
    volume_device_id: '65398894'
    player_name: media_player.mediabox
    OK: Enter
    Button1:
      name: MNu
      command: Menu
      tooltip: Menu

**Comment by ArnolddeBolster** [comment]
is this what you're looking for ?

                         <div class="ok_button ripple item_2_c"
                            style="border: solid 2px ${c}"
                            @click=${()=>{var t,e;return this._button(null!==(e=null===(t=this.config.activities[this._current_activity])||void 0===t?void 0:t.OK)&&void 0!==e?e:"OK")}}>
                         OK</div>

do i understand it right that OK results in OK instead of Enter ?

**Comment by ArnolddeBolster** [comment]
I'm terribely sorry for I found it out and it workes well.
OK in combination with the deviceid had to be 'Select' instead of 'Enter'

If it's OK by you this feature request/bug report can be closed and I make separate feature request instead.

**Comment by ArnolddeBolster** [comment]
made seperate feature requets for open items 
this can be closed
