### ISSUE TITLE
VolumeDown reacts the same as VolumeUP

### ISSUE THREAD

**Issue by ArnolddeBolster** [dezihh/my-harmony-card#6]
My VolumeDown reacts still the same as VolumeUp so i can not reduce volume.

With the madmicio's remote I do not have this problem

I somewhere have read that in some cases volumeup and down command are very close to eachother.

**Comment by dezihh** [comment]
Hi,
normally it can not be. Please enable debug and see, which command is sent when you press volume.
Please check too, if both commands (VolumeUp and VolumeDown) existing for the device in harmony.conf

**Comment by ArnolddeBolster** [comment]
MyCard code:
type: custom:my-harmony-card
name: Harmony
entity: remote.woonkamer
tooltip: true
activities:
  PowerOff:
    name: Poweroff
    device_id: -1
  TV kijken:
    name: '41379770'
    device_id: '65398896'
    volume_device_id: '65398894'
    player_name: media_player.mediabox
    OK: Enter
    Button1:
      name: MNu
      command: Menu
      tooltip: Menu
    Button2:
      name: Txt
      command: Teletext
      tooltip: Teletext
    Button3:
      name: Gui
      command: Guide
      tooltip: Guide
    Button4:
      name: DVR
      command: DVR
      tooltip: DVR
  Radio luisteren DAB:
    name: '41379771'
    device_id: '65398893'
    volume_device_id: '65398893'
    player_name: media_player.room1
    Button1:
      name: prv
      command: PresetPrev
      tooltip: PresetPrev
    Button2:
      name: nxt
      command: PresetNext
      tooltip: PresetNext
    Button3: null
    Button4: null
dimensions:
  scale: '0.99'
  border_width: 2px

and my harmony conf code:
        "Tv Samsung": {
            "commands": [
                "PowerOff",
                "PowerOn",
                "PowerToggle",
                "0",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "Mute",
                "VolumeDown",
                "VolumeUp",
                "ChannelPrev",
                "ChannelDown",
                "ChannelUp",
                "DirectionDown",
                "DirectionLeft",
                "DirectionRight",
                "DirectionUp",
                "Select",
                "Stop",
                "Play",
                "Rewind",
                "Pause",
                "FastForward",
                "Record",
                "Return",
                "Menu",
                "Subtitle",
                "Teletext",
                "TeletextSize",
                "C",
                "B",
                "D",
                "A",
                "Green",
                "Red",
                "Blue",
                "Yellow",
                "Guide",
                "Info",
                "Exit",
                "Aspect",
                "3D",
                "AD",
                "Camera",
                "ChannelList",
                "Content",
                "InputAv",
                "InputComponent",
                "InputExt1",
                "InputExt2",
                "InputHdmi1",
                "InputHdmi2",
                "InputHdmi3",
                "InputHdmi4",
                "InputPc",
                "InputTv",
                "InputUsb",
                "Internet",
                "Media.P",
                "Source",
                "TeletextCancel",
                "TeletextHold",
                "TeletextIndex",
                "TeletextMode",
                "TeletextNextPage",
                "TeletextPreviousPage",
                "TeletextReveal",
                "TeletextStore",
                "TeletextSubPage",
                "Tools",
                "Yamaha_HDMI2"
            ],
            "id": "65398894"

And I am working in IT but feel really realy dumb. 
I try to understand how to debug but my knowledge of that is poor
For you as developer it's probably piece of cake

**Comment by ArnolddeBolster** [comment]
strange, several tries and now it's working suddenly.
this is solved
