### ISSUE TITLE
Feature request: ACT more in front ?

### ISSUE THREAD

**Issue by ArnolddeBolster** [dezihh/my-harmony-card#7]
This remote is beautiful but could distinguish itsself with ACT more in front instead of behind the ACT.
Another advantage would direct 1 push instead 2 just like the hardware version
![image](https://github.com/dezihh/my-harmony-card/assets/71195708/30baaa66-1432-4e22-a594-a5cb5c24fac6)

An improvement for me would be the have is more this way:

something like this
![image](https://github.com/dezihh/my-harmony-card/assets/71195708/0a09a52f-9a4a-4033-828d-8e4de2d4d7f9)

**Comment by dezihh** [comment]
Good idea. I thought about it too. There is one disadvantage: The remote is getting bigger.
Maybe both options in one via configuration. Lets see, if more people are insterested :-)

**Comment by ArnolddeBolster** [comment]
I realised that too, but maybe some buttons rows can made optional.
e.g. when I listen to radio I do not need all TV buttons and when I need more buttons they are mostly for settings or setup.

**Comment by ArnolddeBolster** [comment]
maybe you can make at least the activated activity visible on front?

**Comment by dezihh** [comment]
Your last idea sounds good to me. :-)

**Comment by dezihh** [comment]
Your activity is since v1.30 at he frontpage
