### ISSUE TITLE
Feature request: extra Buttons 5-8 for extra row functions

### ISSUE THREAD

**Issue by ArnolddeBolster** [dezihh/my-harmony-card#9]
I would like to have an optons to use icons for the extra buttonsrow(s) e.g.:
![image](https://github.com/dezihh/my-harmony-card/assets/71195708/116fa5bc-854c-47bf-a5e8-f12b2d46fddc)

**Comment by ArnolddeBolster** [comment]
Now the Button1-4 are available with commands (big improvement  !!!)
could you please add an extra 5-8 button row for the functions of my setup box from ziggo ?
(see bottom row)

**Comment by dezihh** [comment]
Is it the same as in Post #15?

**Comment by ArnolddeBolster** [comment]
not exactly, the extra buttonrow is for the extra functions for my setupbox.

Post #15 could be part of it if the solution is capability for service calls / actions

**Comment by dezihh** [comment]
Global buttons for service calls are since v1.30 available
